### ISSUE TITLE
When installing, a WebProfilerBundle class is not found

### ISSUE THREAD

**Issue by PunchyRascal** [symfony/profiler-pack#4]
```shell
$ composer require --dev symfony/profiler-pack
Using version ^1.0 for symfony/profiler-pack
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 8 installs, 0 updates, 0 removals
  - Installing twig/twig (v2.4.8): Loading from cache
  - Installing symfony/polyfill-php72 (v1.8.0): Loading from cache
  - Installing symfony/var-dumper (v4.1.0): Loading from cache
  - Installing symfony/twig-bridge (v4.1.0): Loading from cache
  - Installing symfony/web-profiler-bundle (v4.1.0): Loading from cache
  - Installing symfony/twig-bundle (v4.1.0): Loading from cache
  - Installing symfony/stopwatch (v4.1.0): Loading from cache
  - Installing symfony/profiler-pack (v1.0.3): Loading from cache
Writing lock file
Generating autoload files
Symfony operations: 2 recipes (f0b543d5da3456ea0ed23935ec334cee)
  - Configuring symfony/web-profiler-bundle (>=3.3): From github.com/symfony/recipes:master
  - Configuring symfony/twig-bundle (>=3.3): From github.com/symfony/recipes:master
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!
!!  Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "WebProfilerBundle" from namespace "Symfony\Bundle\WebProfilerBundle".
!!  Did you forget a "use" statement for another namespace? in C:\Users\i\WEBZ\zbks\src\Kernel.php:33
!!  Stack trace:
!!  #0 C:\Users\i\WEBZ\zbks\vendor\symfony\http-kernel\Kernel.php(409): App\Kernel->registerBundles()
!!  #1 C:\Users\i\WEBZ\zbks\vendor\symfony\http-kernel\Kernel.php(120): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 C:\Users\i\WEBZ\zbks\vendor\symfony\framework-bundle\Console\Application.php(65): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 C:\Users\i\WEBZ\zbks\vendor\symfony\console\Application.php(145): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
!!  #4 C:\Users\i\WEBZ\zbks\bin\console(39): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
!!  #5 {main}
!!    thrown in C:\Users\i\WEBZ\zbks\src\Kernel.php on line 33
!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "WebProfilerBundle" from namespace "Symfony\Bundle\WebProfilerBundle".
!!  Did you forget a "use" statement for another namespace? in C:\Users\i\WEBZ\zbks\src\Kernel.php:33
!!  Stack trace:
!!  #0 C:\Users\i\WEBZ\zbks\vendor\symfony\http-kernel\Kernel.php(409): App\Kernel->registerBundles()
!!  #1 C:\Users\i\WEBZ\zbks\vendor\symfony\http-kernel\Kernel.php(120): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 C:\Users\i\WEBZ\zbks\vendor\symfony\framework-bundle\Console\Application.php(65): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 C:\Users\i\WEBZ\zbks\vendor\symfony\console\Application.php(145): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
!!  #4 C:\Users\i\WEBZ\zbks\bin\console(39): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
!!  #5 {main}
!!    thrown in C:\Users\i\WEBZ\zbks\src\Kernel.php on line 33
!!
Script @auto-scripts was called via post-update-cmd
```

**Comment by PunchyRascal** [comment]
Basically anything I try to add to a clean symfony installation via composer ends up like this - some class missing... profiler, twig, checker...

**Comment by irene1972** [comment]
I have given the same error :(
